In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('profiles.csv')

C:\Users\hfran\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
df.head()

age       body_type               diet    drinks      drugs  \
0  22.0  a little extra  strictly anything  socially      never   
1  35.0         average       mostly other     often  sometimes   
2  38.0            thin           anything  socially        NaN   
3  23.0            thin         vegetarian  socially        NaN   
4  29.0        athletic                NaN  socially      never   

                           education  \
0      working on college/university   
1              working on space camp   
2     graduated from masters program   
3      working on college/university   
4  graduated from college/university   

                                              essay0  \
0  about me:<br />\n<br />\ni would love to think...   
1  i am a chef: this is what that means.<br />\n1...   
2  i'm not ashamed of much, but writing public te...   
3          i work in a library and go to school. . .   
4  hey how's it going? currently vague on the pro...   

                                              essay1  \
0  currently working as an international agent fo...   
1  dedicating everyday to being an unbelievable b...   
2  i make nerdy software for musicians, artists, ...   
3          reading things written by old dead people   
4                         work work work work + play   

                                              essay2  \
0  making people laugh.<br />\nranting about a go...   
1  being silly. having ridiculous amonts of fun w...   
2  improvising in different contexts. alternating...   
3  playing synthesizers and organizing books acco...   
4  creating imagery to look at:<br />\nhttp://bag...   

                                              essay3  ...  \
0  the way i look. i am a six foot half asian, ha...  ...   
1                                                NaN  ...   
2  my large jaw and large glasses are the physica...  ...   
3                  socially awkward but i do my best  ...   
4            i smile a lot and my inquisitive nature  ...   

                          location  \
0  south san francisco, california   
1              oakland, california   
2        san francisco, california   
3             berkeley, california   
4        san francisco, california   

                                      offspring orientation  \
0  doesn&rsquo;t have kids, but might want them    straight   
1  doesn&rsquo;t have kids, but might want them    straight   
2                                           NaN    straight   
3                       doesn&rsquo;t want kids    straight   
4                                           NaN    straight   

                        pets                                  religion sex  \
0  likes dogs and likes cats     agnosticism and very serious about it   m   
1  likes dogs and likes cats  agnosticism but not too serious about it   m   
2                   has cats                                       NaN   m   
3                 likes cats                                       NaN   m   
4  likes dogs and likes cats                                       NaN   m   

                                 sign     smokes  \
0                              gemini  sometimes   
1                              cancer         no   
2  pisces but it doesn&rsquo;t matter         no   
3                              pisces         no   
4                            aquarius         no   

                                              speaks     status  
0                                            english     single  
1  english (fluently), spanish (poorly), french (...     single  
2                               english, french, c++  available  
3                           english, german (poorly)     single  
4                                            english     single  

[5 rows x 31 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60552 entries, 0 to 60551
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   age          9514 non-null   float64
 1   body_type    8666 non-null   object 
 2   diet         5761 non-null   object 
 3   drinks       9012 non-null   object 
 4   drugs        7215 non-null   object 
 5   education    8459 non-null   object 
 6   essay0       8667 non-null   object 
 7   essay1       8347 non-null   object 
 8   essay2       8049 non-null   object 
 9   essay3       7690 non-null   object 
 10  essay4       7879 non-null   object 
 11  essay5       7814 non-null   object 
 12  essay6       7352 non-null   object 
 13  essay7       7553 non-null   object 
 14  essay8       6361 non-null   object 
 15  essay9       7554 non-null   object 
 16  ethnicity    8565 non-null   object 
 17  height       9514 non-null   float64
 18  income       9514 non-null   float64
 19  job 

In [5]:
df.isnull().sum()

age            51038
body_type      51886
diet           54791
drinks         51540
drugs          53337
education      52093
essay0         51885
essay1         52205
essay2         52503
essay3         52862
essay4         52673
essay5         52738
essay6         53200
essay7         52999
essay8         54191
essay9         52998
ethnicity      51987
height         51038
income         51038
job            52369
last_online    51038
location       51038
offspring      56666
orientation    51038
pets           54200
religion       54291
sex            51038
sign           52776
smokes         51956
speaks         51044
status         51038
dtype: int64

In [6]:
df=df.iloc[:9514] # sondaki boş kısımları siliyoruz

In [7]:
df['orientation'].unique()

array(['straight', 'bisexual', 'gay'], dtype=object)

In [8]:
df['body_type'].unique()

array(['a little extra', 'average', 'thin', 'athletic', 'fit', nan,
       'skinny', 'curvy', 'full figured', 'jacked', 'rather not say',
       'used up', 'overweight'], dtype=object)

In [9]:
df=df.drop(['essay0','essay1','essay2','essay3','essay4','essay5','essay6','essay7','essay8','essay9'],axis=1)

In [10]:
df.shape, df.columns

((9514, 21),
 Index(['age', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'ethnicity',
        'height', 'income', 'job', 'last_online', 'location', 'offspring',
        'orientation', 'pets', 'religion', 'sex', 'sign', 'smokes', 'speaks',
        'status'],
       dtype='object'))

In [11]:
df['status'].unique()

array(['single', 'available', 'seeing someone', 'married'], dtype=object)

In [12]:
df['body_type'].unique()

array(['a little extra', 'average', 'thin', 'athletic', 'fit', nan,
       'skinny', 'curvy', 'full figured', 'jacked', 'rather not say',
       'used up', 'overweight'], dtype=object)

In [13]:
df.replace({'athletic':'fit','curv':'full figured','rather not say':'nan','0':'nan'},inplace=True)
df.replace({'used up':'thin','skinny':'thin','a little extra':'average'},inplace=True)

In [14]:
df['body_type'].unique()

array(['average', 'thin', 'fit', nan, 'curvy', 'full figured', 'jacked',
       'nan', 'overweight'], dtype=object)

In [15]:
df['body_type'].value_counts()

fit             3928
average         2704
thin            1056
curvy            626
full figured     181
overweight        69
jacked            64
nan               38
Name: body_type, dtype: int64

In [16]:
df['diet'].unique()

array(['strictly anything', 'mostly other', 'anything', 'vegetarian', nan,
       'mostly anything', 'mostly vegetarian', 'strictly vegan',
       'strictly vegetarian', 'mostly vegan', 'strictly other',
       'mostly halal', 'other', 'vegan', 'mostly kosher',
       'strictly halal', 'halal', 'strictly kosher', 'kosher'],
      dtype=object)

In [17]:
df['diet']=df['diet'].str.replace('mostly','').str.replace('strictly','')

In [18]:
df.replace({'other':'anything'})

age   body_type        diet    drinks      drugs  \
0     22.0     average    anything  socially      never   
1     35.0     average       other     often  sometimes   
2     38.0        thin    anything  socially        NaN   
3     23.0        thin  vegetarian  socially        NaN   
4     29.0         fit         NaN  socially      never   
...    ...         ...         ...       ...        ...   
9509  28.0         fit    anything  socially      never   
9510  31.0         fit    anything  socially  sometimes   
9511  34.0     average         NaN  socially        NaN   
9512  29.0         fit    anything    rarely      never   
9513  49.0  overweight         NaN    rarely      never   

                              education            ethnicity  height   income  \
0         working on college/university         asian, white    75.0     -1.0   
1                 working on space camp                white    70.0  80000.0   
2        graduated from masters program                  NaN    68.0     -1.0   
3         working on college/university                white    71.0  20000.0   
4     graduated from college/university  asian, black, other    66.0     -1.0   
...                                 ...                  ...     ...      ...   
9509              working on med school                white    73.0  60000.0   
9510                                NaN                white    72.0     -1.0   
9511  dropped out of college/university                white    71.0     -1.0   
9512                   two-year college                white    70.0     -1.0   
9513  graduated from college/university                white    64.0     -1.0   

                              job  ...                         location  \
0                  transportation  ...  south san francisco, california   
1            hospitality / travel  ...              oakland, california   
2                             NaN  ...        san francisco, california   
3                         student  ...             berkeley, california   
4     artistic / musical / writer  ...        san francisco, california   
...                           ...  ...                              ...   
9509            medicine / health  ...        san francisco, california   
9510         hospitality / travel  ...        san francisco, california   
9511         hospitality / travel  ...        san francisco, california   
9512                          NaN  ...        san francisco, california   
9513                          nan  ...        castro valley, california   

                                              offspring orientation  \
0          doesn&rsquo;t have kids, but might want them    straight   
1          doesn&rsquo;t have kids, but might want them    straight   
2                                                   NaN    straight   
3                               doesn&rsquo;t want kids    straight   
4                                                   NaN    straight   
...                                                 ...         ...   
9509            doesn&rsquo;t have kids, but wants them    straight   
9510                                                NaN         gay   
9511                            doesn&rsquo;t want kids         gay   
9512  doesn&rsquo;t have kids, and doesn&rsquo;t wan...         gay   
9513                                                NaN    straight   

                           pets                                  religion sex  \
0     likes dogs and likes cats     agnosticism and very serious about it   m   
1     likes dogs and likes cats  agnosticism but not too serious about it   m   
2                      has cats                                       NaN   m   
3                    likes cats                                       NaN   m   
4     likes dogs and likes cats                                       NaN   m   
...                         ...                                       ...  ..   
9509

In [19]:
df['drinks'].unique()

array(['socially', 'often', 'not at all', 'rarely', nan, 'very often',
       'desperately'], dtype=object)

In [20]:
del df['religion']

In [21]:
df.replace({'often':2, 'very often':3, 'desperately':4, 'rarely':1,'socially':1,'not at all':0}, inplace=True)

In [22]:
df['drugs'].unique()

array(['never', 'sometimes', nan, 2], dtype=object)

In [23]:
df.replace({'never':0,'sometimes':1,'often':2},inplace=True)

In [24]:
df['education'].unique()

array(['working on college/university', 'working on space camp',
       'graduated from masters program',
       'graduated from college/university', 'working on two-year college',
       nan, 'graduated from high school', 'working on masters program',
       'graduated from space camp', 'college/university',
       'dropped out of space camp', 'graduated from ph.d program',
       'graduated from law school', 'working on ph.d program',
       'two-year college', 'graduated from two-year college',
       'working on med school', 'dropped out of college/university',
       'space camp', 'graduated from med school',
       'dropped out of high school', 'working on high school',
       'masters program', 'dropped out of ph.d program',
       'dropped out of two-year college', 'dropped out of med school',
       'high school', 'working on law school', 'law school',
       'dropped out of masters program', 'ph.d program',
       'dropped out of law school'], dtype=object)

In [25]:
df.replace({'working on college/university':5, 'working on space camp':5,
       'graduated from masters program':9,
       'graduated from college/university':6, 'working on two-year college':2,
       'nan':0, 'graduated from high school':1, 'working on masters program':9,
       'graduated from space camp':5, 'college/university':5,
       'dropped out of space camp':5, 'graduated from ph.d program':13,
       'graduated from law school':7, 'working on ph.d program':12,
       'two-year college':2, 'graduated from two-year college':3,
       'working on med school':5, 'dropped out of college/university':6,
       'space camp':5, 'graduated from med school':6,
       'dropped out of high school':0, 'working on high school':0,
       'masters program':8, 'dropped out of ph.d program':10,
       'dropped out of two-year college':1, 'dropped out of med school':4,
       'high school':1, 'working on law school':4, 'law school':6,
       'dropped out of masters program':7, 'ph.d program':11,
       'dropped out of law school':4},inplace=True)

In [26]:
df['education'].unique()

array([ 5.,  9.,  6.,  2., nan,  1., 13.,  7., 12.,  3.,  0.,  8., 10.,
        4., 11.])

In [27]:
df['job'].isnull().sum()

1331

In [28]:
df['job'].mode()

0    other
dtype: object

In [29]:
df['job']=df['job'].fillna('other')

In [30]:
df['location'].mode()

0    san francisco, california
dtype: object

In [31]:
df['location'][df['ethnicity']=='white'].mode()

0    san francisco, california
dtype: object

In [32]:
df['ethnicity']=df['ethnicity'].fillna('white')

In [33]:
df['pets'].unique()

array(['likes dogs and likes cats', 'has cats', 'likes cats', nan,
       'has dogs and likes cats', 'likes dogs and has cats',
       'likes dogs and dislikes cats', 'has dogs',
       'has dogs and dislikes cats', 'likes dogs',
       'has dogs and has cats', 'dislikes dogs and has cats',
       'dislikes dogs and dislikes cats', 'dislikes cats',
       'dislikes dogs and likes cats', 'dislikes dogs'], dtype=object)

In [34]:
df['pets'].mode()

0    likes dogs and likes cats
dtype: object

In [35]:
df['pets']=df['pets'].fillna('likes dogs and likes cats')

In [36]:
df['pets'].unique()

array(['likes dogs and likes cats', 'has cats', 'likes cats',
       'has dogs and likes cats', 'likes dogs and has cats',
       'likes dogs and dislikes cats', 'has dogs',
       'has dogs and dislikes cats', 'likes dogs',
       'has dogs and has cats', 'dislikes dogs and has cats',
       'dislikes dogs and dislikes cats', 'dislikes cats',
       'dislikes dogs and likes cats', 'dislikes dogs'], dtype=object)

In [37]:
df['offspring'].mode()

0    doesn&rsquo;t have kids
dtype: object

In [38]:
df['offspring']=df['offspring'].fillna('doesn&rsquo;t have kids')

In [39]:
df['smokes'].unique()

array([1, 'no', nan, 'when drinking', 'yes', 'trying to quit'],
      dtype=object)

In [40]:
df['smokes'].replace({'no':0,'when drinking':1, 'yes':1, 'trying to quit':0},inplace=True)

In [41]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [42]:
df['status'].unique()

array(['single', 'available', 'seeing someone', 'married'], dtype=object)

In [43]:
df['status']=le.fit_transform(df['status'])

In [44]:
df['status'].unique()

array([3, 0, 2, 1])

In [45]:
df['drugs']=df['drugs'].fillna(0)

In [46]:
df['height']=df['height'].astype('int')
df['income']=df['income'].astype('int')
df['sex']=le.fit_transform(df['sex'])

### Filling missing values of smokes with XGBRegressor

In [47]:
df['smokes'].unique()

array([ 1.,  0., nan])

In [48]:
fill=df[df['smokes'].notnull()]
null=df[df['smokes'].isnull()]
fill['smokes']=fill['smokes'].astype('int')
fill['drugs']=fill['drugs'].astype('int')
fill.shape

C:\Users\hfran\AppData\Local\Temp/ipykernel_1176/3371370588.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fill['smokes']=fill['smokes'].astype('int')
C:\Users\hfran\AppData\Local\Temp/ipykernel_1176/3371370588.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fill['drugs']=fill['drugs'].astype('int')


(8596, 20)

In [49]:
x=fill[['age','height','sex','status','drugs']]
y=fill['smokes']
x.shape, y.shape

((8596, 5), (8596,))

In [50]:
from xgboost import XGBRegressor

In [51]:
xgbr=XGBRegressor()

In [52]:
xgbr.fit(x,y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=12,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [53]:
x=null[['age','height','sex','status','drugs']]
y=null['smokes']
x.shape,y.shape

((918, 5), (918,))

In [54]:
pred_smoke=xgbr.predict(x)

In [55]:
df.loc[df['smokes'].isnull(),'smokes']=xgbr.predict(x)
df['smokes'].isnull().sum()

0

### Filling missing value of education with XGBRegressor

In [56]:
df['education'].unique()

array([ 5.,  9.,  6.,  2., nan,  1., 13.,  7., 12.,  3.,  0.,  8., 10.,
        4., 11.])

In [57]:
fill=df[df['education'].notnull()]
null=df[df['education'].isnull()]
fill.shape

(8459, 20)

In [58]:
x=fill[['age','smokes','sex','status','drugs']]
y=fill['education']
x.shape, y.shape

((8459, 5), (8459,))

In [59]:
from xgboost import XGBRegressor
xgbr=XGBRegressor()
xgbr.fit(x,y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=12,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [60]:
x=null[['age','smokes','sex','status','drugs']]
y=null['education']
x.shape,y.shape

((1055, 5), (1055,))

In [61]:
df.loc[df['education'].isnull(),'education']=xgbr.predict(x)
df['education'].isnull().sum()

0

### Filling missing value of body_type with XGBRegressor

In [62]:
df['body_type'].unique()

array(['average', 'thin', 'fit', nan, 'curvy', 'full figured', 'jacked',
       0, 'overweight'], dtype=object)

In [63]:
df['body_type']=df['body_type'].replace({0:'nan'})

In [64]:
df['body_type'].unique()

array(['average', 'thin', 'fit', nan, 'curvy', 'full figured', 'jacked',
       'nan', 'overweight'], dtype=object)

In [65]:
fill=df[df['body_type'].notnull()]
null=df[df['body_type'].isnull()]
fill['body_type']=le.fit_transform(fill['body_type'])
fill.shape

C:\Users\hfran\AppData\Local\Temp/ipykernel_1176/1169225882.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fill['body_type']=le.fit_transform(fill['body_type'])


(8666, 20)

In [66]:
fill['body_type'].unique()

array([0, 7, 2, 1, 3, 4, 5, 6])

In [67]:
x=fill[['age','height','education','smokes','sex','status','drugs']]
y=fill['body_type']
x.shape, y.shape

((8666, 7), (8666,))

In [68]:
from xgboost import XGBRegressor
xgbr=XGBRegressor()
xgbr.fit(x,y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=12,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [69]:
x=null[['age','height','education','smokes','sex','status','drugs']]
y=null['body_type']
x.shape,y.shape

((848, 7), (848,))

In [70]:
df.loc[df['body_type'].isnull(),'body_type']=xgbr.predict(x)
df['body_type'].isnull().sum()

0

### Filling missing value of drinks with XGBRegressor

In [71]:
df['drinks'].unique()

array([ 1.,  2.,  0., nan,  3.,  4.])

In [72]:
fill=df[df['drinks'].notnull()]
null=df[df['drinks'].isnull()]
fill.shape

(9012, 20)

In [73]:
x=fill[['age','smokes','drugs']]
y=fill['drinks']
x.shape, y.shape

((9012, 3), (9012,))

In [74]:
from xgboost import XGBRegressor
xgbr=XGBRegressor()
xgbr.fit(x,y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=12,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [75]:
x=null[['age','smokes','drugs']]
y=null['drinks']
x.shape,y.shape

((502, 3), (502,))

In [76]:
df.loc[df['drinks'].isnull(),'drinks']=xgbr.predict(x)
df['drinks'].isnull().sum()

0

### Filling missing value of diet with XGBRegressor

In [77]:
df['diet'].unique()

array([' anything', ' other', 'anything', 'vegetarian', nan,
       ' vegetarian', ' vegan', ' halal', 'other', 'vegan', ' kosher',
       'halal', 'kosher'], dtype=object)

In [78]:
fill=df[df['diet'].notnull()]
null=df[df['diet'].isnull()]
fill['diet']=le.fit_transform(fill['diet'])
fill.shape

C:\Users\hfran\AppData\Local\Temp/ipykernel_1176/3817502262.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fill['diet']=le.fit_transform(fill['diet'])


(5761, 20)

In [79]:
x=fill[['age','height','smokes','sex','status','drugs','drinks']]
y=fill['diet']
x.shape, y.shape

((5761, 7), (5761,))

In [80]:
from xgboost import XGBRegressor
xgbr=XGBRegressor()
xgbr.fit(x,y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=12,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [81]:
x=null[['age','height','smokes','sex','status','drugs','drinks']]
y=null['diet']
x.shape, y.shape

((3753, 7), (3753,))

In [82]:
df.loc[df['diet'].isnull(),'diet']=xgbr.predict(x)
df['diet'].isnull().sum()

0

In [83]:
df.isnull().sum()

age               0
body_type         0
diet              0
drinks            0
drugs             0
education         0
ethnicity         0
height            0
income            0
job               0
last_online       0
location          0
offspring         0
orientation       0
pets              0
sex               0
sign           1738
smokes            0
speaks            6
status            0
dtype: int64

In [84]:
del df['sign']

In [85]:
df.isnull().sum()

age            0
body_type      0
diet           0
drinks         0
drugs          0
education      0
ethnicity      0
height         0
income         0
job            0
last_online    0
location       0
offspring      0
orientation    0
pets           0
sex            0
smokes         0
speaks         6
status         0
dtype: int64

In [86]:
from catboost import CatBoostRegressor,CatBoostClassifier
from sklearn.ensemble import AdaBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

In [87]:
df=pd.get_dummies(df)

In [88]:
df

age  drinks  drugs  education  height  income  sex  smokes  status  \
0     22.0     1.0    0.0   5.000000      75      -1    1     1.0       3   
1     35.0     2.0    1.0   5.000000      70   80000    1     0.0       3   
2     38.0     1.0    0.0   9.000000      68      -1    1     0.0       0   
3     23.0     1.0    0.0   5.000000      71   20000    1     0.0       3   
4     29.0     1.0    0.0   6.000000      66      -1    1     0.0       3   
...    ...     ...    ...        ...     ...     ...  ...     ...     ...   
9509  28.0     1.0    0.0   5.000000      73   60000    1     0.0       3   
9510  31.0     1.0    1.0   6.426177      72      -1    1     1.0       3   
9511  34.0     1.0    0.0   6.000000      71      -1    1     1.0       3   
9512  29.0     1.0    0.0   2.000000      70      -1    1     0.0       3   
9513  49.0     1.0    0.0   6.000000      64      -1    0     0.0       3   

      body_type_0.025342073291540146  ...  speaks_english, turkish  \
0                                  0  ...                        0   
1                                  0  ...                        0   
2                                  0  ...                        0   
3                                  0  ...                        0   
4                                  0  ...                        0   
...                              ...  ...                      ...   
9509                               0  ...                        0   
9510                               0  ...                        0   
9511                               0  ...                        0   
9512                               0  ...                        0   
9513                               0  ...                        0   

      speaks_english, turkish (fluently), italian (okay)  \
0                                                     0    
1                                                     0    
2                                                     0    
3                                                     0    
4                                                     0    
...                                                 ...    
9509                                                  0    
9510                                                  0    
9511                                                  0    
9512                                                  0    
9513                                                  0    

      speaks_english, turkish, c++  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   
...                            ...   
9509                             0   
9510                             0   
9511                             0   
9512                             0   
9513                             0   

      speaks_english, urdu, french, arabic, russian (poorly)  \
0                                                     0        
1                                                     0        
2                                                     0        
3                                                     0        
4                                                     0        
...                                                 ...        
9509                                                  0        
9510                                                  0        
9511                                                  0        
9512                                                  0        
9513                                                  0        

      speaks_english, vietnamese  speaks_english, vietnamese (okay)  \
0                              0                                  0   
1                              0                                  0   
2                              0                                  0   
3         

In [89]:
y=df['age']
x=df.drop('age',axis=1)

In [90]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)

In [91]:
model = CatBoostRegressor(iterations=100,
                          learning_rate=1,
                          depth=3)

In [92]:
model.fit(x_train, y_train)

0:	learn: 8.4639141	total: 154ms	remaining: 15.2s
1:	learn: 8.1311303	total: 165ms	remaining: 8.06s
2:	learn: 7.9883221	total: 175ms	remaining: 5.66s
3:	learn: 7.9135840	total: 186ms	remaining: 4.45s
4:	learn: 7.7655075	total: 196ms	remaining: 3.72s
5:	learn: 7.6745853	total: 206ms	remaining: 3.22s
6:	learn: 7.6606418	total: 216ms	remaining: 2.87s
7:	learn: 7.6095650	total: 225ms	remaining: 2.59s
8:	learn: 7.6020929	total: 235ms	remaining: 2.38s
9:	learn: 7.5670910	total: 244ms	remaining: 2.2s
10:	learn: 7.5473657	total: 254ms	remaining: 2.05s
11:	learn: 7.5071506	total: 263ms	remaining: 1.93s
12:	learn: 7.4934421	total: 273ms	remaining: 1.82s
13:	learn: 7.4750810	total: 282ms	remaining: 1.73s
14:	learn: 7.4478653	total: 291ms	remaining: 1.65s
15:	learn: 7.4358594	total: 300ms	remaining: 1.58s
16:	learn: 7.4100997	total: 309ms	remaining: 1.51s
17:	learn: 7.3983668	total: 318ms	remaining: 1.45s
18:	learn: 7.3875221	total: 326ms	remaining: 1.39s
19:	learn: 7.3550031	total: 336ms	remainin

In [93]:
preds = model.predict(x_test)
preds

array([53.97998782, 30.72464715, 47.58544457, ..., 32.95735351,
       34.30780184, 27.76050057])

In [94]:
(mean_squared_error(y_test,preds))**2

3158.813469469409

In [95]:
r2_score(y_test,preds)

0.35145487302962863